# Generated by Django 5.1.6 on 2025-02-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidor', '0002_servidor_cidade_servidor_lotacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='funcao',
            field=models.CharField(default='', max_length=50),
        ),
    ]
